addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"       % "0.10.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"       % "2.4.6")
addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.14.2")
addSbtPlugin("com.dwijnand"   % "sbt-dynver"         % "4.1.1")
addSbtPlugin("com.github.sbt" % "sbt-pgp"            % "2.1.2")
